# Generated by Django 2.1.5 on 2019-08-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190801_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
    ]
