# Generated by Django 2.1.5 on 2019-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_photo_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photo_1',
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
