# Generated by Django 2.1.5 on 2019-07-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20190724_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='is_mvp',
        ),
    ]
