# Generated by Django 2.1.5 on 2019-07-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
