# Generated by Django 2.1.5 on 2019-07-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20190725_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
    ]
