# Generated by Django 2.1.5 on 2019-07-26 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20190725_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
    ]
