# Generated by Django 2.1.5 on 2019-07-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
